import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { SVGFilters } from '@/components/SVGFilters'
// TODO 自定义字体
// See: https://nextjs.org/docs/app/building-your-application/optimizing/fonts#local-fonts
import { Bowlby_One_SC, DM_Mono } from 'next/font/google'
import '@/styles/globals.css'

const bowlby = Bowlby_One_SC({
  subsets: ['latin'],
  variable: '--font-bowlby-sc',
  display: 'swap',
  weight: '400',
})

const dmMono = DM_Mono({
  subsets: ['latin'],
  variable: '--font-dm-mono',
  display: 'swap',
  weight: '500',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlby.variable} ${dmMono.variable} antialiased font-mono font-medium text-zinc-800`}
      >
        <Header />
        <main>{children}</main>
        <SVGFilters />
      </body>
    </html>
  )
}
